///////////////////////////////////////////////////////////
//  Arbeidstaker.cs
//  Implementation of the Class Arbeidstaker
//  Generated by Enterprise Architect
//  Created on:      19-sep-2016 09.38.11
//  Original author: Tor Kjetil
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Arbeidstaker;
using Person;
namespace Arbeidstaker {
	/// <summary>
	/// Alle ressurser i HR
	/// </summary>
	public class Arbeidstaker : Person {

		private Tidsperiode ansettelsesdato;
		private Kontaktinformasjon2 kontaktinformasjon;
		private Stilling stillinger;

		public Arbeidstaker(){

		}

		~Arbeidstaker(){

		}

	}//end Arbeidstaker

}//end namespace Arbeidstaker